import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="w-full bg-gray-900 border-b border-blue-400 mb-8">
          <div className="max-w-5xl mx-auto flex items-center justify-between px-6 py-4">
            <div className="text-2xl font-bold text-blue-300">UnderDogs AI</div>
            <div className="flex gap-6">
              <a href="/" className="text-blue-200 hover:text-blue-400 font-semibold transition">Home</a>
              <a href="/dashboard" className="text-blue-200 hover:text-blue-400 font-semibold transition">Dashboard</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
